//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellenceIT.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_City
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_City()
        {
            this.TBL_Employee = new HashSet<TBL_Employee>();
        }
    
        public int CityID { get; set; }
        public string Name { get; set; }
        public Nullable<int> StateID { get; set; }
    
        public virtual TBL_State TBL_State { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Employee> TBL_Employee { get; set; }
    }
}
